// src/utils/mockData.js

export const FILTER_OPTIONS = {
  genre: ['All Genres', 'Fiction', 'Tech', 'Business', 'Self-Help', 'Classic', 'Mythology', 'Poetry', 'History'],
  language: ['All Languages', 'English', 'Hindi', 'Marathi'],
  ageGroup: ['All Ages', '0-5 Years', '6-8 Years', '9-12 Years', 'Young Adult', 'Adult']
};

export const INITIAL_BOOKS = [
  { id: 1, title: 'The Pragmatic Programmer', author: 'David Thomas', genre: 'Tech', language: 'English', ageGroup: 'Adult', publisher: 'Addison-Wesley', year: '1999', pages: 352, availableCopies: 4, cover: 'https://covers.openlibrary.org/b/isbn/9780135957059-M.jpg', isTrending: true, isRecommended: false, isComingSoon: false },
  { id: 2, title: 'Clean Code', author: 'Robert C. Martin', genre: 'Tech', language: 'English', ageGroup: 'Adult', publisher: 'Prentice Hall', year: '2008', pages: 464, availableCopies: 0, cover: 'https://covers.openlibrary.org/b/isbn/9780132350884-M.jpg', isTrending: true, isRecommended: true, isComingSoon: false },
  { id: 3, title: 'Dune', author: 'Frank Herbert', genre: 'Fiction', language: 'English', ageGroup: 'Young Adult', publisher: 'Chilton Books', year: '1965', pages: 412, availableCopies: 2, cover: 'https://covers.openlibrary.org/b/isbn/9780441172719-M.jpg', isTrending: true, isRecommended: true, isComingSoon: false },
  { id: 4, title: 'Godan', author: 'Munshi Premchand', genre: 'Classic', language: 'Hindi', ageGroup: 'Adult', publisher: 'Saraswati Press', year: '1936', pages: 368, availableCopies: 1, cover: 'https://covers.openlibrary.org/b/isbn/9788188440053-M.jpg', isTrending: false, isRecommended: true, isComingSoon: false },
  { id: 5, title: 'Atomic Habits', author: 'James Clear', genre: 'Self-Help', language: 'English', ageGroup: 'Adult', publisher: 'Avery', year: '2018', pages: 320, availableCopies: 8, cover: 'https://covers.openlibrary.org/b/isbn/9780735211292-M.jpg', isTrending: true, isRecommended: true, isComingSoon: false },
  { id: 6, title: 'Yayati', author: 'V. S. Khandekar', genre: 'Mythology', language: 'Marathi', ageGroup: 'Adult', publisher: 'Deshmukh & Co', year: '1959', pages: 432, availableCopies: 3, cover: 'https://covers.openlibrary.org/b/isbn/9788177665245-M.jpg', isTrending: false, isRecommended: true, isComingSoon: false },
  { id: 7, title: 'Project Hail Mary', author: 'Andy Weir', genre: 'Fiction', language: 'English', ageGroup: 'Adult', publisher: 'Ballantine Books', year: '2021', pages: 496, availableCopies: 5, cover: 'https://covers.openlibrary.org/b/isbn/9780593135204-M.jpg', isTrending: true, isRecommended: false, isComingSoon: false },
  { id: 8, title: 'Deep Work', author: 'Cal Newport', genre: 'Business', language: 'English', ageGroup: 'Adult', publisher: 'Grand Central', year: '2016', pages: 304, availableCopies: 2, cover: 'https://covers.openlibrary.org/b/isbn/9781455586691-M.jpg', isTrending: false, isRecommended: true, isComingSoon: false },
  { id: 9, title: 'The Winds of Winter', author: 'George R.R. Martin', genre: 'Fiction', language: 'English', ageGroup: 'Adult', publisher: 'Bantam Books', year: '2026', pages: 1024, availableCopies: 0, cover: 'https://covers.openlibrary.org/b/isbn/9780002247412-M.jpg', isTrending: false, isRecommended: false, isComingSoon: true },
  { id: 10, title: 'Madhushala', author: 'Harivansh Rai Bachchan', genre: 'Poetry', language: 'Hindi', ageGroup: 'Adult', publisher: 'Rajpal & Sons', year: '1935', pages: 144, availableCopies: 4, cover: 'https://covers.openlibrary.org/b/isbn/9788121601053-M.jpg', isTrending: true, isRecommended: true, isComingSoon: false },
  { id: 11, title: 'Diary of a Wimpy Kid', author: 'Jeff Kinney', genre: 'Fiction', language: 'English', ageGroup: '9-12 Years', publisher: 'Amulet Books', year: '2007', pages: 224, availableCopies: 6, cover: 'https://covers.openlibrary.org/b/isbn/9780141324906-M.jpg', isTrending: true, isRecommended: false, isComingSoon: false },
  { id: 12, title: 'The Very Hungry Caterpillar', author: 'Eric Carle', genre: 'Fiction', language: 'English', ageGroup: '0-5 Years', publisher: 'World Publishing', year: '1969', pages: 26, availableCopies: 1, cover: 'https://covers.openlibrary.org/b/isbn/9780241003008-M.jpg', isTrending: false, isRecommended: true, isComingSoon: false },
  { id: 13, title: 'Introduction to Algorithms', author: 'Thomas H. Cormen', genre: 'Tech', language: 'English', ageGroup: 'Adult', publisher: 'MIT Press', year: '2009', pages: 1312, availableCopies: 2, cover: 'https://covers.openlibrary.org/b/isbn/9780262033848-M.jpg', isTrending: false, isRecommended: true, isComingSoon: false },
  { id: 14, title: 'Sapiens', author: 'Yuval Noah Harari', genre: 'History', language: 'English', ageGroup: 'Adult', publisher: 'Harvill Secker', year: '2014', pages: 464, availableCopies: 7, cover: 'https://covers.openlibrary.org/b/isbn/9780062316097-M.jpg', isTrending: true, isRecommended: true, isComingSoon: false },
  { id: 15, title: '1984', author: 'George Orwell', genre: 'Classic', language: 'English', ageGroup: 'Young Adult', publisher: 'Secker & Warburg', year: '1949', pages: 328, availableCopies: 0, cover: 'https://covers.openlibrary.org/b/isbn/9780451524935-M.jpg', isTrending: false, isRecommended: true, isComingSoon: false },
  { id: 21, title: 'The Art of War', author: 'Sun Tzu', genre: 'Classic', language: 'English', ageGroup: 'Adult', publisher: 'Shambhala', year: '2005', pages: 112, cover: 'https://covers.openlibrary.org/b/isbn/9781590302255-M.jpg', isTrending: false, isRecommended: false, isComingSoon: false, isEbook: true },
  { id: 22, title: 'Meditations', author: 'Marcus Aurelius', genre: 'Classic', language: 'English', ageGroup: 'Adult', publisher: 'Modern Library', year: '2002', pages: 256, cover: 'https://covers.openlibrary.org/b/isbn/9780812968255-M.jpg', isTrending: false, isRecommended: false, isComingSoon: false, isEbook: true },
];